name: core_location_fluttify
description: A new Flutter project.
version: 0.7.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/core_location_fluttify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.13.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.core_location_fluttify
        pluginClass: CoreLocationFluttifyPlugin
      ios:
        pluginClass: CoreLocationFluttifyPlugin